### PR TITLE
Added travis and codecov

### PR DESCRIPTION
**Pull request by andriisoldatenko**
@fafhrd91 please review.
Could you please enable travis and codecov to this repo.

### CODE REVIEW

**Comment by fafhrd91** [comment]
@andriisoldatenko you should have have added access to this repo

**Comment by andriisoldatenko** [comment]
@fafhrd91 hmm...I didn't see any emails from github about access to this repo.
image

**Comment by fafhrd91** [comment]
Do you see "settings" tab?

**Comment by andriisoldatenko** [comment]
@fafhrd91  Nope.
https://www.evernote.com/l/AMNarLiXeZNPi639k1dvjmY5E4w6FwTKGYU

**Comment by andriisoldatenko** [comment]
@fafhrd91 fixed.

**Comment by fafhrd91** [comment]
good, then just merge PR and add travis

**Comment by fafhrd91** [comment]
i had to rebase master, you should re-fork or just work in branches in main repo.

**Pull request merged**
